version: '3.8'

services:
  spark-master:
    image: bde2020/spark-master:3.2.1-hadoop3.2
    container_name: agoda_data_pipline_clone-spark-master-1
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./data:/data
      - ./jobs:/jobs

  spark-worker:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    depends_on:
      - spark-master
    volumes:
      - ./data:/data
      - ./jobs:/jobs

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=agoda
      - POSTGRES_PASSWORD=agoda
      - POSTGRES_DB=agoda_data
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
