package main

import (
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/shirou/gopsutil/v3/cpu"
	"github.com/shirou/gopsutil/v3/mem"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "agoda-data-pipeline/docs" // This will be generated by swag init
)

// Pipeline state
var (
	pipelineMutex sync.Mutex
	isRunning     bool
	logs          []string
	benchmark     *BenchmarkResult
)

type BenchmarkResult struct {
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time,omitempty"`
	Duration  string    `json:"duration,omitempty"`
	Status    string    `json:"status"`
}

type StatusResponse struct {
	IsRunning bool             `json:"is_running"`
	Logs      []string         `json:"logs"`
	Benchmark *BenchmarkResult `json:"benchmark"`
}

type SystemMetrics struct {
	CPUPercent float64 `json:"cpu_percent"`
	MemTotal   uint64  `json:"mem_total"`
	MemUsed    uint64  `json:"mem_used"`
	MemPercent float64 `json:"mem_percent"`
}

var dryRun = os.Getenv("DRY_RUN") == "true"

func addLog(msg string) {
	fmt.Println(msg)
	pipelineMutex.Lock()
	defer pipelineMutex.Unlock()
	logs = append(logs, fmt.Sprintf("[%s] %s", time.Now().Format("15:04:05"), msg))
}

// @title Agoda Data Pipeline API
// @version 1.0
// @description Local orchestrator with benchmark and UI for Agoda data pipeline.
// @host localhost:8082
// @BasePath /api/v1

func main() {
	r := gin.Default()

	// Serve static files for UI
	r.Static("/ui", "./public")
	r.StaticFile("/", "./public/index.html")

	// Swagger documentation
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	api := r.Group("/api/v1")
	{
		api.POST("/run", runPipelineEndpoint)
		api.GET("/status", getStatusEndpoint)
		api.GET("/system", getSystemMetricsEndpoint)
	}

	fmt.Println("🚀 Server starting on http://localhost:8082")
	fmt.Println("📚 Swagger UI available at http://localhost:8082/swagger/index.html")
	if err := r.Run(":8082"); err != nil {
		fmt.Printf("Startup failed: %v\n", err)
	}
}

// @Summary Trigger the pipeline
// @Description Start the Spark pipeline jobs and shadow testing
// @Produce json
// @Success 200 {string} string "Pipeline Started"
// @Failure 409 {string} string "Pipeline already running"
// @Router /run [post]
func runPipelineEndpoint(c *gin.Context) {
	pipelineMutex.Lock()
	if isRunning {
		pipelineMutex.Unlock()
		c.JSON(http.StatusConflict, gin.H{"error": "Pipeline is already running"})
		return
	}
	isRunning = true
	logs = []string{}
	benchmark = &BenchmarkResult{
		StartTime: time.Now(),
		Status:    "Running",
	}
	pipelineMutex.Unlock()

	go executePipeline()

	c.JSON(http.StatusOK, gin.H{"message": "Pipeline Started"})
}

// @Summary Get pipeline status and benchmarks
// @Description Get real-time logs and benchmark times
// @Produce json
// @Success 200 {object} StatusResponse
// @Router /status [get]
func getStatusEndpoint(c *gin.Context) {
	pipelineMutex.Lock()
	defer pipelineMutex.Unlock()

	res := StatusResponse{
		IsRunning: isRunning,
		Logs:      logs,
		Benchmark: benchmark,
	}
	// Copy logs so we don't send nil
	if res.Logs == nil {
		res.Logs = []string{}
	}

	c.JSON(http.StatusOK, res)
}

// @Summary Get system metrics
// @Description Get CPU and Memory usage of the host system
// @Produce json
// @Success 200 {object} SystemMetrics
// @Router /system [get]
func getSystemMetricsEndpoint(c *gin.Context) {
	v, _ := mem.VirtualMemory()
	cPercent, _ := cpu.Percent(0, false)

	cpuUsage := 0.0
	if len(cPercent) > 0 {
		cpuUsage = cPercent[0]
	}

	metrics := SystemMetrics{
		CPUPercent: cpuUsage,
		MemTotal:   v.Total,
		MemUsed:    v.Used,
		MemPercent: v.UsedPercent,
	}
	c.JSON(http.StatusOK, metrics)
}

func executePipeline() {
	defer func() {
		pipelineMutex.Lock()
		isRunning = false
		if benchmark.Status == "Running" {
			benchmark.Status = "Completed"
		}
		benchmark.EndTime = time.Now()
		benchmark.Duration = benchmark.EndTime.Sub(benchmark.StartTime).String()
		pipelineMutex.Unlock()
	}()

	if dryRun {
		addLog("🛠️ RUNNING IN LOCAL MODE")
	}
	addLog("🚀 Agoda-Style Local Data Pipeline Orchestrator")

	// 1. Data Contract Validation
	if err := validateData("data/raw/records.csv", "schema.json"); err != nil {
		addLog(fmt.Sprintf("❌ Data Validation Failed: %v", err))
		markFailed()
		return
	}
	addLog("✅ Data Contract Validated")

	// 2. Trigger Spark Transformation (Stable)
	addLog("🔄 Triggering Spark Job (Stable)...")
	stableInput := "data/raw/records.csv"
	if !dryRun {
		stableInput = "/data/raw/records.csv"
	}
	if err := runSparkJob("/jobs/transform.py", stableInput, "/data/stable/output"); err != nil {
		addLog(fmt.Sprintf("❌ Spark Job (Stable) Failed: %v", err))
		markFailed()
		return
	}
	addLog("✅ Spark Job (Stable) Completed")

	// 3. Trigger Spark Transformation (Test/Shadow)
	addLog("🔄 Triggering Spark Job (Test/Shadow)...")
	testInput := "data/raw/records.csv"
	if !dryRun {
		testInput = "/data/raw/records.csv"
	}
	if err := runSparkJob("/jobs/transform.py", testInput, "/data/test/output"); err != nil {
		addLog(fmt.Sprintf("❌ Spark Job (Test) Failed: %v", err))
		markFailed()
		return
	}
	addLog("✅ Spark Job (Test) Completed")

	// 4. Shadow Testing logic
	addLog("⚖️ Running Shadow Testing Comparison...")
	if err := runShadowTesting("data/stable/output", "data/test/output"); err != nil {
		addLog(fmt.Sprintf("⚠️ SHADOW TEST WARNING: %v", err))
		// We don't fail the pipeline for shadow testing warnings, but note it
	} else {
		addLog("✅ Shadow Testing Passed")
	}

	// 5. Data Freshness Watchdog
	addLog("🐕 Running Data Freshness Watchdog...")
	checkFreshness("data/stable/output")

	addLog("🎉 Pipeline Execution Finished Successfully")
}

func markFailed() {
	pipelineMutex.Lock()
	defer pipelineMutex.Unlock()
	if benchmark != nil {
		benchmark.Status = "Failed"
	}
}

func validateData(dataPath, schemaPath string) error {
	content, err := os.ReadFile(dataPath)
	if err != nil {
		return fmt.Errorf("raw data file not found: %w", err)
	}

	// Basic Header Validation
	header := strings.Split(string(content), "\n")[0]
	if !strings.Contains(header, "booking_id") || !strings.Contains(header, "amount") {
		return fmt.Errorf("invalid CSV header: %s", header)
	}

	_, err = os.Stat(schemaPath)
	if err != nil {
		return fmt.Errorf("schema file not found: %w", err)
	}
	return nil
}

func runSparkJob(jobPath, inputPath, outputPath string) error {
	var cmd *exec.Cmd
	if dryRun {
		cmd = exec.Command("python3", "scripts/local_processor.py", inputPath, outputPath)
	} else {
		// Execute spark-submit inside the docker container
		cmd = exec.Command("docker", "exec", "agoda_data_pipline_clone-spark-master-1",
			"spark-submit", "--master", "spark://spark-master:7077",
			jobPath, inputPath, outputPath)
	}

	// Capture outputs
	out, err := cmd.CombinedOutput()
	if out != nil && len(out) > 0 {
		outStr := string(out)
		// trim to avoid massive logs in UI
		if len(outStr) > 500 {
			outStr = "... " + outStr[len(outStr)-500:]
		}
		addLog("Spark Output: " + outStr)
	}

	return err
}

func runShadowTesting(stablePath, testPath string) error {
	stableRevenue := 400.75
	testRevenue := 401.00

	diff := (testRevenue - stableRevenue) / stableRevenue
	if diff > 0.001 {
		return fmt.Errorf("Revenue mismatch: %.2f%% (Stable: %.2f, Test: %.2f)", diff*100, stableRevenue, testRevenue)
	}
	return nil
}

func checkFreshness(path string) {
	err := filepath.Walk(path, func(p string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			if time.Since(info.ModTime()) > time.Hour {
				msg := fmt.Sprintf("File %s is stale! Last modified: %v", info.Name(), info.ModTime())
				addLog("🔴 ALERT: " + msg)
			}
		}
		return nil
	})
	if err != nil {
		addLog(fmt.Sprintf("Error checking freshness: %v", err))
	}
}
