// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/run": {
            "post": {
                "description": "Start the Spark pipeline jobs and shadow testing",
                "produces": [
                    "application/json"
                ],
                "summary": "Trigger the pipeline",
                "responses": {
                    "200": {
                        "description": "Pipeline Started",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Pipeline already running",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Get real-time logs and benchmark times",
                "produces": [
                    "application/json"
                ],
                "summary": "Get pipeline status and benchmarks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.StatusResponse"
                        }
                    }
                }
            }
        },
        "/system": {
            "get": {
                "description": "Get CPU and Memory usage of the host system",
                "produces": [
                    "application/json"
                ],
                "summary": "Get system metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SystemMetrics"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.BenchmarkResult": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "main.StatusResponse": {
            "type": "object",
            "properties": {
                "benchmark": {
                    "$ref": "#/definitions/main.BenchmarkResult"
                },
                "is_running": {
                    "type": "boolean"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "main.SystemMetrics": {
            "type": "object",
            "properties": {
                "cpu_percent": {
                    "type": "number"
                },
                "mem_percent": {
                    "type": "number"
                },
                "mem_total": {
                    "type": "integer"
                },
                "mem_used": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Agoda Data Pipeline API",
	Description:      "Local orchestrator with benchmark and UI for Agoda data pipeline.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
